apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki-svc:3100
    jsonData:
      timeout: 60
      maxLines: 1000
      derivedFields:
        - datasourceUid: jaeger
          matcherRegex: ((\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+)(\d+|[a-z]+))
          url: "$${__value.raw}"
          name: TraceID
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: http://prometheus-svc:9090
    jsonData:
      timeInterval: "5s"
      maxLines: 1000
  - name: Jaeger
    type: jaeger
    uid: jaeger
    access: proxy
    url: http://jaeger-svc:16686
  - name: tempo
    type: tempo
    uid: tempo
    access: browser
    url: http://tempo-svc:16686
    isDefault: false
    version: 1
    editable: true
    basicAuth: false
