name: Go Test Coverage Report On Main Branch
on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: go mod vendor
      - name: Test with the Go CLI
        id: test
        run: go test -coverprofile=unit.coverage.out ./...
      - name: Upload coverage report
        id: coverage
        env:
          CODACY_API_TOKEN: ${{ secrets.CODACY_API_TOKEN }}
          CODACY_ORGANIZATION_PROVIDER: gh
          CODACY_USERNAME: ${{ github.repository_owner }}
          CODACY_PROJECT_NAME: ${{ github.event.repository.name }}
        run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
              --force-coverage-parser go -r unit.coverage.out
